-- Add autoPublish flag to SocialAccount
-- When true, content generated by ContentAgent will automatically create social posts for this account
ALTER TABLE "SocialAccount" ADD COLUMN IF NOT EXISTS "autoPublish" BOOLEAN NOT NULL DEFAULT FALSE;

-- Schedule config: { type: 'immediate'|'peak_hours'|'custom', customSlots?: string[], customDays?: string[] }
ALTER TABLE "SocialAccount" ADD COLUMN IF NOT EXISTS "autoPublishSchedule" JSONB DEFAULT NULL;

-- Index for efficient lookup: find all auto-publish accounts for a project
CREATE INDEX IF NOT EXISTS "SocialAccount_projectId_autoPublish_idx"
  ON "SocialAccount"("projectId")
  WHERE "autoPublish" = TRUE AND "isActive" = TRUE;
